server{
      
      #nginx listens on port 80
      listen 80;

      #serve frontend html

      location / {
	      root /usr/share/nginx/html;
	      index index.html;
      }
      
       # ── Proxy API calls to Node.js container ─────────────────
    # Any request to /api/... gets forwarded to the app container
    # "app" is the Docker service name — Docker DNS resolves it

      location /api/ {
	      proxy_pass  http://app:3000;
	      proxy_http_version 1.1;
	      proxy_set_header  Host $host;
	      proxy_set_header X-Real-IP $remote_addr;

      }

      #proxy health check

      location /health/ {
	      proxy_pass http://app:3000;
      }


}
